#!/usr/bin/env python

"""
Script to make an animated XCRYSDEN file from a vasp NEB run
Requires structure_tools.py

Use  neb_axsf [0/1] to write the .axsf file from POSCAR/CONTCAR files
"""

import sys
import os
import structure_tools as st

###############  MAIN  #######################
# Default to looking at POSCARs
carfile = "POSCAR"
outfile = "movie.axsf"

if len(sys.argv) >= 2 and sys.argv[1] == "1":
	print "using CONTCARs to make movie file"
	carfile = "CONTCAR"


# Make a list for images
imagelist = []

# Loop over all of the possible images
for i in range(100):

	if i < 10:
		dirname = '0{0}'.format(i)
	else:
		dirname = str(i)

	# Quit the loop if there are no more images
	if os.path.isdir('./{0}'.format(dirname)):
		imagefile = dirname+"/"+carfile
	else:
		break

	# Now read the carfile and add image to the image list
	image = st.Structure()

	# Allow for reading POSCAR of end images
	try:
		st.read_poscar(image, imagefile)
	except:
		st.read_poscar(image, dirname+"/POSCAR")

	# Add image to image list
	imagelist.append(image)

st.write_axsf( imagelist, outfile )
